version: '3.9'
services:
    component:
        image: "tmacam/dapr-memstore-java:latest"
        environment:
            - DAPR_COMPONENT_SOCKET_PATH=/var/run/dapr-state.javamemstore-v1-myjavamemstore.sock
        volumes:
            - socket:/var/run
    daprd:
        image: "ghcr.io/mcandeia/daprd:1.9.0-pluggable-components-alpha.4-linux-amd64"
        command: "./daprd --app-id pluggable-test --components-path=/components"
        depends_on:
            - component
        ports:
            - "3500:3500"
        volumes:
            - socket:/var/run
            - ./config:/components
volumes:
    socket: