name: Build

on:
  push:
    branches:
      - master
      - main
      - release-*
    tags:
      - v*

  pull_request:
    branches:
    - master
    - main
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    env:
      GOVER: 1.19
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://proxy.golang.org
      JDK_VER: ${{ matrix.java }}
      DAPR_CLI_VER: 1.8.0-rc.1
      DAPR_RUNTIME_VER: 1.8.0-rc.3
      DAPR_INSTALL_URL: https://raw.githubusercontent.com/dapr/cli/v1.8.0-rc.1/install/install.sh
      DAPR_REF: 683a436ff1367e4ff2d27da2d79069c04ec2c46d
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up OpenJDK ${{ env.JDK_VER }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VER }}
      - name: Clean up files
        run: mvn clean
      - name: Build sdk
        run: mvn compile --quiet
      - name: Unit tests
        run: mvn test --quiet
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
